### ISSUE TITLE
Dark mode in Feature Teacher and Feature Student

### ISSUE THREAD

**Issue by HarshitPandey251** [Akshima-Ghai/OneEducationalWebsiteForAll#103]
As There is no implementation of Dark mode in Feature Teacher and Feature Student page it will shown like this

![Screenshot 2021-07-10 104546](https://user-images.githubusercontent.com/69616901/125152985-4d08b300-e16e-11eb-8699-5d45128df832.jpg)

I want to work on it and assign under devincept @Akshima-Ghai

**Comment by Akshima-Ghai** [comment]
@HarshitPandey251 issue assigned , just improve the UI of buttons for dark mode
