### ISSUE TITLE
Website Logo

### ISSUE THREAD

**Issue by AfraMP** [Akshima-Ghai/OneEducationalWebsiteForAll#104]
I have tried out some logos...
1.
![LearnZania1](https://user-images.githubusercontent.com/48359218/125154194-7af1f580-e176-11eb-9722-07cb4feb311a.png)
2.
![LearnZania2](https://user-images.githubusercontent.com/48359218/125154207-8b09d500-e176-11eb-8f88-399160466326.png)
3.
![LearnZania3](https://user-images.githubusercontent.com/48359218/125154226-9fe66880-e176-11eb-8085-43ea1ea51402.png)

**Comment by Akshima-Ghai** [comment]
@AfraMP attach each logo to our website and send the ss of each page with the logo. The logo which suits our website the most, we will commit the changes

**Comment by AfraMP** [comment]
![Screenshot (75)](https://user-images.githubusercontent.com/48359218/125187520-a8f63900-e24d-11eb-9975-1cd1145b3719.png)
![Screenshot (74)](https://user-images.githubusercontent.com/48359218/125187576-dd69f500-e24d-11eb-8352-b3410bfa94bd.png)
![Screenshot (76)](https://user-images.githubusercontent.com/48359218/125187588-f8d50000-e24d-11eb-9b16-db57bbdfb8ed.png)

**Comment by Akshima-Ghai** [comment]
@AfraMP keep the second logo , also keep the name LearnZania like before to the right of logo , don't remove that . 
Apply the changes and share the ss then we will commit the changes applied

**Comment by AfraMP** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/48359218/125219514-7ea28b00-e2e2-11eb-80af-0908586fdff7.png)

**Comment by Akshima-Ghai** [comment]
@AfraMP you can create a pr, with the following changes. Great Work
