### ISSUE TITLE
Create CODE-OF-CONDUCT.md file

### ISSUE THREAD

**Issue by Sitanshu-AI** [Akshima-Ghai/OneEducationalWebsiteForAll#107]
Create a code of conduct  for those who are new to open source.

**Comment by swathi-469** [comment]
Please assign this to me .. I would like to work on it

**Comment by Sitanshu-AI** [comment]
I think this is assigned to those who raised the issue

**Comment by deeqakkk** [comment]
@Sitanshu-AI Can you describe a bit more about what you want to add?

**Comment by deeqakkk** [comment]
> I think this is assigned to those who raised the issue

Sitanshu its not like issue will be assigned to only those who opened it, assignment depands on who asked for it first.
And also in some cases multiple contributors can work on single issue.

**Comment by swathi-469** [comment]
So can I start working on it

**Comment by Akshima-Ghai** [comment]
@swathi-469 issue assigned

**Comment by swathi-469** [comment]
I have made my pull request can check it

**Comment by Sitanshu-AI** [comment]
i have raised the issue how can you assigned it to other person

**Comment by Akshima-Ghai** [comment]
@Sitanshu-AI you have to ask for the assignment of issue if u want to work on the issue . Only creating won't help us to keep track ,who is willing to work on the issue, pls keep that in mind for future references

**Comment by HarshitPandey251** [comment]
I want to work on it @deeqakkk

**Comment by Akshima-Ghai** [comment]
@HarshitPandey251 issue assigned

**Comment by swathi-469** [comment]
Sir I have already made my pull request and got merged but you are still assigning it. And not closed the issue

**Comment by deeqakkk** [comment]
> Sir I have already made my pull request and got merged but you are still assigning it. And not closed the issue

oh, sorry my bad I misinterpreted it with some other issue.
@HarshitPandey251 this issue is already resolved, you can look for another one.
