### ISSUE TITLE
store preference

### ISSUE THREAD

**Issue by VenomFate-619** [Akshima-Ghai/OneEducationalWebsiteForAll#108]
When a user toggle to dark mode , then its preference should be **set to dark mode** means if i refresh the page know , it should remains in dark mode rather than light mode .

**Comment by VenomFate-619** [comment]
can i work on it?

**Comment by deeqakkk** [comment]
@VenomFate-619 Go ahead.

**Comment by VenomFate-619** [comment]
Help 🆘 
I want to set the theme on initial loading according to system theme , for that i am using ```useMediaQuery``` hook but there is a flask between light and dark mode , i tried this [solution](https://github.com/mui-org/material-ui/issues/15588) but not work.
If you or me get any solution , then it will get implemented or i will drop it (I think may be it will also require to make the theme state global so that checkbox can access it)


https://user-images.githubusercontent.com/67755128/125206264-07e69d00-e2a4-11eb-97d2-a115727c13df.mp4

**Comment by deeqakkk** [comment]
@VenomFate-619 Your idea seems nice but currently we are not looking into user's system for anything, so just try toggling it between dark and light mode using button on webpage only.
