### ISSUE TITLE
Fix responisveness in mobile view for "Get Started" Section

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#110]
![image](https://user-images.githubusercontent.com/78724676/125196173-73197a80-e276-11eb-9d92-87fcdce2ac25.png)
![image](https://user-images.githubusercontent.com/78724676/125196174-744aa780-e276-11eb-85fb-bd705ff09a67.png)
![image](https://user-images.githubusercontent.com/78724676/125196176-76ad0180-e276-11eb-9231-271cb8aa022b.png)
![image](https://user-images.githubusercontent.com/78724676/125196180-77de2e80-e276-11eb-91a5-0a207c32be37.png)

Changes Required:
1.when in mobile view there should be single background instead of multiple same images 
2. Align them to center
3. Fix positons of social media handles as well(specially github )
4. remove this extra padding as well
![image](https://user-images.githubusercontent.com/78724676/125196324-1f5b6100-e277-11eb-9c2c-70c1fad2db03.png)

**Comment by HarshitPandey251** [comment]
I want to work on this issue

**Comment by Akshima-Ghai** [comment]
@HarshitPandey251 issue assigned

**Comment by HarshitPandey251** [comment]
In this page dark mode is not working, so I change that as well
