### ISSUE TITLE
Change position of "login" & "signup" button in mobile view.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#111]
Expected positons.
![image](https://user-images.githubusercontent.com/78724676/125196738-89283a80-e278-11eb-9b5a-e088621dff3b.png)

Don't make major changes in design and color theme.
Check responsiveness before making a PR.

**Comment by Swastik1710** [comment]
Can you please assign this issue to me?

**Comment by Akshima-Ghai** [comment]
@Swastik1710 issue assigned

**Comment by Swastik1710** [comment]
Hey, shall I also remove the login and signup options from sidebar menu ?

**Comment by Swastik1710** [comment]
Here's how it is looking
![2](https://user-images.githubusercontent.com/71871571/125223437-671ad080-e2e9-11eb-8f0f-82f4ab27f3b0.jpg)

![1](https://user-images.githubusercontent.com/71871571/125223432-63874980-e2e9-11eb-883a-67cd02f13a60.jpg)

**Comment by deeqakkk** [comment]
Yes, Swastik they are fine but change the color of the buttons.
both of them need not be of the same color and same hover effect.
and also check for responsiveness before making a PR.
