### ISSUE TITLE
Fix positon of "back to top " button in mobile view.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#112]
Check for responsiveness before making a PR.

**Comment by Swastik1710** [comment]
Please assign this issue to me.

**Comment by Akshima-Ghai** [comment]
@Swastik1710 issue assigned

**Comment by Swastik1710** [comment]
Hey @deeqakkk 
All you want is that the scroll to top button doesn't go out from the right margin.
Or is there something else that needs to be done ?

**Comment by deeqakkk** [comment]
No, nothing else just make it visible in mobile screen as well.
