### ISSUE TITLE
Apply dark theme in All section 

### ISSUE THREAD

**Issue by AmanBisht01** [Akshima-Ghai/OneEducationalWebsiteForAll#119]
Dark theme is not applied on all section 

![Screenshot (122)](https://user-images.githubusercontent.com/59495320/125244274-c0e0c200-e30c-11eb-996f-939f605de583.png)

**Comment by AmanBisht01** [comment]
Assign this issue to me .

**Comment by HarshitPandey251** [comment]
I already working on this issue  as  issue #110 where I have to do changes, So in which I solve this issue also

**Comment by AmanBisht01** [comment]
Ok go ahead
