### ISSUE TITLE
Can i work on the homepage

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#12]
** Description **

HomePage for the OneEducationWebsite

## Changes to be Made

 - Folder Structure
 - Add HomePage
 - Regular Color Scheme
 - Will Use ReactJS

**Comment by Akshima-Ghai** [comment]
@NikhilSharma03 issue assigned. All the best, try to learn maximum from the opportunity given.
