### ISSUE TITLE
Fix the gap generated between footer of the website and browser window.

### ISSUE THREAD

**Issue by shrihari-07** [Akshima-Ghai/OneEducationalWebsiteForAll#122]
As shown in the below picture, the gap between the browser window and footer needs to fixed.
![Screenshot from 2021-07-12 18-48-54](https://user-images.githubusercontent.com/67782171/125294621-0c619300-e342-11eb-87f5-78ae52caf02f.png)

**Comment by shrihari-07** [comment]
Can I fix it?

**Comment by deeqakkk** [comment]
@shrihari-07 It was nice that you observed this, but this issue is alredy there in #110.
explore a bit more maybe you can get some issues to fix or a new feature to add on🤠
