### ISSUE TITLE
Change Scroll Bar style in our webiste.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#123]
Keep its theme same as our website theme.
you can share a ss of your idea before you start working on it.

**Comment by shrihari-07** [comment]
@deeqakkk I can try to work on it.

**Comment by Akshima-Ghai** [comment]
@shrihari-07 issue assigned

**Comment by shrihari-07** [comment]
@Akshima-Ghai @deeqakkk Please check the below shown scroll-bar style and let me know if there is any changes needed.
![Screenshot from 2021-07-16 15-18-41](https://user-images.githubusercontent.com/67782171/125928829-ab8009cb-c1b3-42f7-b139-dd91327dfb91.png)

**Comment by Akshima-Ghai** [comment]
It looks good , u can create a pr for these changes
