### ISSUE TITLE
Add a suitable "Favicon" 

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#124]
![image](https://user-images.githubusercontent.com/78724676/125341151-ec959380-e370-11eb-8eb1-ac076469895e.png)

Change this React logo to some relatable favicon on our website.

**Comment by HarshitPandey251** [comment]
I want to contribute in this issue @deeqakkk

**Comment by Akshima-Ghai** [comment]
@HarshitPandey251 issue assigned

**Comment by anupamishra333** [comment]
Can i contribute?

**Comment by Akshima-Ghai** [comment]
This issue is already assigned .
@anupamishra333 find a different issue to contribute
