### ISSUE TITLE
Navbar Button 

### ISSUE THREAD

**Issue by Swastik1710** [Akshima-Ghai/OneEducationalWebsiteForAll#130]
As of now the navbar button color is not set for dark mode which doesn't look good.

![2](https://user-images.githubusercontent.com/71871571/125406538-91968780-e3d6-11eb-94a8-4fee79d74a0b.jpg)

I wanna update the colors according to the dark and light theme and also add a hover effect to it.
Demo :

![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/71871571/125406788-d6222300-e3d6-11eb-8f9e-f592a28510a4.gif)

**Comment by Swastik1710** [comment]
Please assign this issue to me.

**Comment by Akshima-Ghai** [comment]
@Swastik1710 issue assigned
