### ISSUE TITLE
Creating backend server

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Akshima-Ghai/OneEducationalWebsiteForAll#133]
- I would like to create a backend server app using express .
- I can create a basic structure of backend server app , so that we can start working on backend.
- server will be connected to mongodb .
- swagger ui can also be added to show backend routes on running server .

@deeqakkk @Akshima-Ghai I'd like to work on this issue under DCP'21 .

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned

**Comment by Akshima-Ghai** [comment]
@NikhilSharma03
