### ISSUE TITLE
NavBar Responsiveness in both dark and light mode

### ISSUE THREAD

**Issue by urmi-256** [Akshima-Ghai/OneEducationalWebsiteForAll#136]
![Screenshot (167)](https://user-images.githubusercontent.com/71149323/125676139-2bff593c-8a04-4ed2-9238-85190be342b3.png)

Navbar toggle button is coming upon sign up. Have to fix navbar responsiveness. Can I work on this issue?

**Comment by Akshima-Ghai** [comment]
@urmi-256 issue assigned

**Comment by urmi-256** [comment]
#[](https://github.com/Akshima-Ghai/OneEducationalWebsiteForAll/pull/143) #
