### ISSUE TITLE
Navbar with Headroom.js

### ISSUE THREAD

**Issue by Harshal0902** [Akshima-Ghai/OneEducationalWebsiteForAll#137]
Replace the fixed navbar using Headroom.Js, i.e. hiding the navbar until its needed. 
[Reference](https://wicky.nillia.ms/headroom.js/)

**Comment by Harshal0902** [comment]
@Akshima-Ghai I am one of the contributor from devincept, can i work on this issue?

**Comment by Akshima-Ghai** [comment]
@Harshal0902 issue assigned
