### ISSUE TITLE
Update "our team" section to display our active contributors in it.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#152]
~Try to make it dynamic so that it changes automatically according to the latest PR summited by a contributor.
~Make it differentiable among Project admin, Mentors, and our contributors.
~one more basic thing as follows
![image](https://user-images.githubusercontent.com/78724676/126042384-a3dcb04b-6006-4172-861f-2a119a81c52e.png)
Change that truck icon to something related to education instead of delivery.

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned
