### ISSUE TITLE
add auth middleware

### ISSUE THREAD

**Issue by VenomFate-619** [Akshima-Ghai/OneEducationalWebsiteForAll#156]
Add middleware to verify that the user is authenticated

**Comment by deeqakkk** [comment]
> Add middleware to verify that the user is authenticated

Describe a bit more so that i can add level accordingly

**Comment by VenomFate-619** [comment]
checking whether jwt token is expired or not

**Comment by deeqakkk** [comment]
> checking whether jwt token is expired or not

Okay, you can work on it.
