### ISSUE TITLE
Add hover effect  in "Get Started section"

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#157]
![image](https://user-images.githubusercontent.com/78724676/126121137-52b9179c-f637-43fc-b82a-f83fcc3a8c90.png)
....hover on test series should show some questions
....hover on more feature should show our "upcoming courses"

 comment if you have any further query.

**Comment by dilroseR** [comment]
Can i get some detailed info on this?

**Comment by deeqakkk** [comment]
you need to change the hover effect according to required changes mentioned in ss.

**Comment by AmanBisht01** [comment]
Please Assign it to me ... 
@deeqakkk

**Comment by deeqakkk** [comment]
@AmanBisht01 Try to make a PR within 3 day.

**Comment by deeqakkk** [comment]
any update @AmanBisht01 ?

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned

**Comment by deeqakkk** [comment]
> I'd like to work on this issue

Reference: https://codepen.io/havardob/pen/gOamzGq
add proper padding to make all the texts center aligned.
stick to our color theme.
