### ISSUE TITLE
Link a Chatbot to Doubt assistance in get started page.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#159]
A pop chatbot on the right bottom with a greeting msg or maybe some quotes.
chatbox should be of around 450px 400px.

You can visit jio chatbot in its app for reference or maybe some other that you have used.

**Comment by urmi-256** [comment]
Can I work on this?

**Comment by Akshima-Ghai** [comment]
@urmi-256 issue assigned

**Comment by urmi-256** [comment]
What other things I will have to add in the chatbot besides greeting. Or can I add by myself according to the issue?

**Comment by Akshima-Ghai** [comment]
@urmi-256  add basic questions abt the website and its features, and if u can think of any other issue, pls add that and make it a good chatbot

**Comment by urmi-256** [comment]
https://user-images.githubusercontent.com/71149323/126631257-17c3d912-2d95-451f-8bf8-43960234f751.mp4

Is this ok?

**Comment by Akshima-Ghai** [comment]
also add "IF U HAVE ANY OTHER DOUBT CONTACT US AT EMAIL OR NUMBER " maybe
else I find it cool .
@deeqakkk if u want to suggest some changes pls mention
great work @urmi-256

**Comment by urmi-256** [comment]
#183

**Comment by urmi-256** [comment]
https://user-images.githubusercontent.com/71149323/126902887-fad1be89-0254-4a75-9ce3-cde10b54b6fd.mp4

Updated accordingly. Is this now ok? Shall I give a fresh pr or add in earlier one only?
@deeqakkk

**Comment by urmi-256** [comment]
https://user-images.githubusercontent.com/71149323/126953944-0b56ec96-19c7-47a0-a194-7911cc7c3065.mp4

Updated accordingly. Is this now ok? Should I create a fresh pr or existing one only? @deeqakkk
