### ISSUE TITLE
Create a blog page and link it with blogs in get started section.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#160]
Blog page needs to show some of our most-read blogs in form of cards with short descriptions and a read more button.

**Comment by AmanBisht01** [comment]
I would like to work on this issue .

**Comment by VenomFate-619** [comment]
I want to do it? Can you explain more what is to be done?

**Comment by deeqakkk** [comment]
Referance:

https://dribbble.com/shots/14170952-Pixelmatters-Blog

**Comment by ShwetKhatri2001** [comment]
@deeqakkk I'd like to work on this issue

**Comment by deeqakkk** [comment]
Sure @ShwetKhatri2001 , try to make a PR soon.
