### ISSUE TITLE
Create a new test/quiz section.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#161]
1. It should only be accessible after logging in.
2. it need to have a timer
3. you can use dummy mcq's for now (i will provide with some questions later on)
4.section showing attempted questions , left questions , questions not visited yet
5. add some basics instructions as well before test starts

Reference: https://cache.careers360.mobi/media/presets/1600X810/articles/uploads/froala_editor/images/2020/10/7/1602061690423.webp

**Comment by NikhilSharma03** [comment]
Would love to work on it

**Comment by Akshima-Ghai** [comment]
@NikhilSharma03 issue assigned
