### ISSUE TITLE
[BackEnd] Email already exist

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#163]
## Description

** Issue **
- In the current Teacher and Student sign-up methods, it is not being checked whether the provided email already exits or not. 
- This will lead to duplicate emails for multiple account.

** Required Changes **
- Check whether the email already exists or not.
- If not, then proceed with the email
- If yes, return error with message "Email already exits"

## Note For Reviews
- Would love to work on it.

**Comment by ShwetKhatri2001** [comment]
Its being checked already based on error code we get for saving new document having duplicate email .

**Comment by NikhilSharma03** [comment]
> Its being checked already based on error code we get for saving new document having duplicate email .

Ok i guess we can use that.
