### ISSUE TITLE
Send reset password link via email for forgot-password

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Akshima-Ghai/OneEducationalWebsiteForAll#165]
- If student / teacher forget password , then his / her email will be taken and an email having reset password frontend-link will be sent.

@deeqakkk @Akshima-Ghai I would like to work on this issue

**Comment by deeqakkk** [comment]
Yes, sure go ahead by adding a forgot password link close to login form.
and share a ss while making a PR.

**Comment by ShwetKhatri2001** [comment]
I was talking about creating a server route for taking email when user forgot password and sending email having reset password frontend route link ( where he will be entering new password ). front-end routes  for forgot - password and reset-password can be made and connected  after this issue.
