### ISSUE TITLE
Side Drawer issue

### ISSUE THREAD

**Issue by HarshitPandey251** [Akshima-Ghai/OneEducationalWebsiteForAll#167]
There is no option of Student and Teacher in Side drawer slide while in mobile view
It was looking like this
![Screenshot 2021-07-20 182727](https://user-images.githubusercontent.com/69616901/126327845-16ffc454-00e6-4a02-95b4-1d67d0721aaa.jpg)

@deeqakkk I want to work on this

**Comment by deeqakkk** [comment]
Yes, go on and solve this.
