### ISSUE TITLE
Feature - Reset Password 

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Akshima-Ghai/OneEducationalWebsiteForAll#171]
- User have been provided a link having password_reset_token , on that frontend link he will be entering new password 
- New password will be updated in db for that student or teacher account, which can be used then onwards

@Akshima-Ghai @deeqakkk I'd like to work on this issue

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned
