### ISSUE TITLE
[FrontEnd] Fix Footer Responsiveness

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#173]
## Description
- The content of the footer overflows the screen width resulting in white spacing.

![Screenshot from 2021-07-21 16-57-02](https://user-images.githubusercontent.com/58226527/126481869-cfdd5e74-8f18-4baa-b4cd-78a24ebe37e3.png)

** Changes To Make **
- Fix the responsiveness issue
- Change the alignment of content for a better UI

## Note For Reveiwers
- Would love to work on this.

**Comment by Akshima-Ghai** [comment]
@NikhilSharma03 issue assigned
