### ISSUE TITLE
Save user contact messages and send relevant emails

### ISSUE THREAD

**Issue by ShwetKhatri2001** [Akshima-Ghai/OneEducationalWebsiteForAll#180]
- Saving messages sent by student / teacher from get in touch section to db model using  a server route
- Sending 'Thanks for contacting' type email to that user.
- Sending email to project admin having user-details ( who contacted ) and message he sent ( user's feedback/ message ).

@Akshima-Ghai I'd like to work on this issue

**Comment by Akshima-Ghai** [comment]
@ShwetKhatri2001 issue assigned
