### ISSUE TITLE
Connect SignUp Forms To Backend API

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#184]
## Description
- Currently, The teacher and student signup forms are not connected with the backend API. 
- Need to make necessary changes in the react app to connect with the backend api.

## Note For Reviewers
- Would love to work on it.

**Comment by deeqakkk** [comment]
any updates?

**Comment by NikhilSharma03** [comment]
@deeqakkk I will make PR by evening.
