### ISSUE TITLE
Add .env.example file in the server directory

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#185]
## Description
- Currently, we are using several environment variables in the backend server.

** Desired Changes **
- It would be good practice if we can add a .env.example file which contains all the environment Variable ( with empty values ) so one can use this file to generate their own .env file

## Note For Reviewers
Would love to work on it.

**Comment by deeqakkk** [comment]
Great idea.👏, even I didn't got this before.
