### ISSUE TITLE
concurrently start

### ISSUE THREAD

**Issue by VenomFate-619** [Akshima-Ghai/OneEducationalWebsiteForAll#200]
The server and Client should start with one command.
By implementing this server will start first then the client, then the client will work properly

**Can I Do it**

**Comment by deeqakkk** [comment]
sure

**Comment by deeqakkk** [comment]
any updates @VenomFate-619

**Comment by VenomFate-619** [comment]
I was  busy in my exams , 
I will try to do it by  tomorrow .
