### ISSUE TITLE
BLOGS Page

### ISSUE THREAD

**Issue by Akshima-Ghai** [Akshima-Ghai/OneEducationalWebsiteForAll#209]
Create a page for blogs sections

**Comment by ShwetKhatri2001** [comment]
I'd like to work on this issue . Any Reference ?

**Comment by NikhilSharma03** [comment]
Would love to work on this issue.

**Comment by ShwetKhatri2001** [comment]
@deeqakkk Can I work on this issue ?

**Comment by deeqakkk** [comment]
> @deeqakkk Can I work on this issue ?

sure!

**Comment by deeqakkk** [comment]
> @Akshima-Ghai I think we can assign this issue to ShwetKhatri. I will work on the last component `Video Lectures`.

Thanks for this teamwork spirit.
