### ISSUE TITLE
Features Video

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#221]
@ShwetKhatri2001 We need some help.

**Comment by NikhilSharma03** [comment]
If possible can you create a demo video of the login/signup/forgot/reach out mailing service we are providing? Since I don't have credentials for SendGrid. Let me know if that's okay with you.
In the meantime, I will create one for the front end for quiz/blog/video lectures, etc. 
@Akshima-Ghai Need to post it on LinkedIn by Sunday.

**Comment by ShwetKhatri2001** [comment]
Ok will do it

**Comment by NikhilSharma03** [comment]
Cool. Thanks Shwet
