### ISSUE TITLE
UI of the website 

### ISSUE THREAD

**Issue by Akshima-Ghai** [Akshima-Ghai/OneEducationalWebsiteForAll#32]
This will first open a page to ask user if he/she is a student or teacher, then accordingly next page will open, including different sections like abt page, the home page, video lectures, DoubtAssitance, Blogs, TestSeries/Quiz Section, and more features. 
We are open to creative design as you like, but keep the standards high .
All the best.

**Comment by urmi-256** [comment]
Can I work on this issue ? If teacher we can provide an add button for him/her to add lectures blogs etc under different sections and even view them.

**Comment by Akshima-Ghai** [comment]
ok @urmi-256 you can work on this issue , but keep the UI creative and get the most learning out of this given opportunity . ALL THE BEST

**Comment by sujith248** [comment]
Can I work this task too, and then you can select the best out of two, only if you are okay with it?

**Comment by Akshima-Ghai** [comment]
sure @sujith248 , go ahead. Try to make the best UI, ALL THE BEST.
