### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by Akshima-Ghai** [Akshima-Ghai/OneEducationalWebsiteForAll#33]
Design a logo , which will best suit our website

**Comment by pranjay-poddar** [comment]
Please assign this task to me.

**Comment by Akshima-Ghai** [comment]
@pranjay-poddar issue assigned, try to make the most suitable logo for the website as well as the app. ALL THE BEST

**Comment by Jagannath8** [comment]
Can I work on this issue?

**Comment by Akshima-Ghai** [comment]
@Jagannath8 go ahead , design a logo . The best logo will be selected . All the best

**Comment by satyapavan99** [comment]
I want to work on this

**Comment by Akshima-Ghai** [comment]
@satyapavan99 go ahead , design a logo . The best logo will be selected. All the best

**Comment by deeqakkk** [comment]
@satyapavan99 @Jagannath8 @pranjay-poddar any updates guys?

**Comment by pranjay-poddar** [comment]
@deeqakkk @Akshima-Ghai sorry for the delay, I have made some of the logo designs have a look at them if you like any of those do let me know then I'll create a pull request.

![1](https://user-images.githubusercontent.com/52539501/124365308-bb2c1200-dc64-11eb-8d1b-8654e7f279b2.png)
![2](https://user-images.githubusercontent.com/52539501/124365309-bc5d3f00-dc64-11eb-8335-833740547dbe.png)
![3](https://user-images.githubusercontent.com/52539501/124365310-bc5d3f00-dc64-11eb-87e4-d83604379e34.png)
![4](https://user-images.githubusercontent.com/52539501/124365311-bcf5d580-dc64-11eb-8523-a1dab3749e97.png)
![5](https://user-images.githubusercontent.com/52539501/124365312-bd8e6c00-dc64-11eb-8b92-75f034dd18f7.png)

**Comment by Jagannath8** [comment]
![Learn ZANIA](https://user-images.githubusercontent.com/64650848/124367345-f4b84980-dc73-11eb-9355-638c2a4b2b84.png)

I've created this logo.

**Comment by deeqakkk** [comment]
@Jagannath8 do share a screenshot here!

**Comment by deeqakkk** [comment]
@pranjay-poddar @Jagannath8 Can you guys update them to some cloud in standard format and share a link here?then you can make a pr.

and also Logo's are really so good👏

**Comment by pranjay-poddar** [comment]
Link To Learn Zania Logo Designs in .PNG format 👇
https://drive.google.com/drive/folders/1u7GBagg3VfEByK2r7-1372-5wLp1Evf2?usp=sharing

@deeqakkk @Akshima-Ghai

**Comment by Jagannath8** [comment]
https://drive.google.com/drive/u/0/folders/1uBNGq9Ct6ga_9OltXiGdE3aBBoWc-8T5

**Comment by deeqakkk** [comment]
Logo has been added in the assests.
