### ISSUE TITLE
Design Website

### ISSUE THREAD

**Issue by Akshima-Ghai** [Akshima-Ghai/OneEducationalWebsiteForAll#38]
Design Teacher/Student Section
Design About Page
Design Doubt Assistance Page
Design Quiz Page
Design Courses Page

**Comment by itsij** [comment]
I would like to work on About Page

**Comment by Akshima-Ghai** [comment]
@itsij go ahead, keep the theme similar to that of the main page. ALL THE BEST

**Comment by ambalika24** [comment]
@Akshima-Ghai Ma'am , I want to design the courses page. I  just want to discuss some ideas with you. Kindly assign this issue to me.

**Comment by Akshima-Ghai** [comment]
@ambalika24 issue assigned , you can discuss the ideas here or on the slack . Try to keep same theme as that of main page and abt page , and make the best UI . ALL THE BEST.

**Comment by AmanBisht01** [comment]
I would like to work on guidance page.

**Comment by Akshima-Ghai** [comment]
@AmanBisht01 , abt page is ready. If u want to make any productive changes. Go ahead

**Comment by yashoda203** [comment]
I would like to work on Quiz page.

**Comment by AmanBisht01** [comment]
I would like to work on doubt assistance page.

**Comment by Akshima-Ghai** [comment]
@yashoda203 , QUIZ PAGE is already assigned to @The-An0rack , you two can discuss with each other and design the UI, or you can pick some other issue.

**Comment by Akshima-Ghai** [comment]
@AmanBisht01 issue assigned, try to keep the theme the same and try to make a great UI. ALL THE BEST.

**Comment by The-An0rack** [comment]
> @yashoda203 , QUIZ PAGE is already assigned to @The-An0rack , you two can discuss with each other and design the UI, or you can pick some other issue.

Sure! a helping hand would be great!

**Comment by SAHU-01** [comment]
@Akshima-Ghai  could you assign me with the Teacher /Student section designs !

**Comment by Akshima-Ghai** [comment]
@SAHU-01 issue assigned, try to keep the theme the same and try to make a great UI. ALL THE BEST.
