### ISSUE TITLE
Resolve Errors

### ISSUE THREAD

**Issue by Akshima-Ghai** [Akshima-Ghai/OneEducationalWebsiteForAll#39]
Maintain CodeBase, if you find any error, just ask for the issue and debug the code.

**Comment by Swastik1710** [comment]
There's an issue in starting up the page on one's local machine.
As given in the documentation, when we run npm start we get the following error.

![Screenshot 2021-07-01 195447](https://user-images.githubusercontent.com/71871571/124146410-5bd6d200-daab-11eb-8cb4-a2e968be18fc.jpg)

And on running npm start ,we get these errors.

![Screenshot 2021-07-01 202210](https://user-images.githubusercontent.com/71871571/124146480-6e510b80-daab-11eb-9bf5-f9eb1b578916.jpg)

We need to solve this problem asap.
I have a solution to this (maybe a temporary fix or so)

**Comment by Akshima-Ghai** [comment]
@Swastik1710 help on the grp and update readme.md , we will check the solution and then would commit your changes

**Comment by Swastik1710** [comment]
Yeah sure.
