### ISSUE TITLE
Responsive Optimization required 

### ISSUE THREAD

**Issue by toth2000** [Akshima-Ghai/OneEducationalWebsiteForAll#47]
# Optimization required for mobile devices.

Issue:
 * Blank space to the right of the navbar.
 * Header Image not  centered
 * Footer white space is not symmetric on the left and right sides.

Steps to reproduce the error:
 - npm start and visit localhost:3000
 - open browser's developer tools (Ctrl+Shift+i)
 
![Screenshot 2021-07-01 132801](https://user-images.githubusercontent.com/65480420/124088030-311b5800-da70-11eb-9c71-6db2dc666b56.png)

**Comment by Akshima-Ghai** [comment]
@toth2000 great work, find more errors so that we can resolve such errors. 
@NikhilSharma03  pls have a look at the errors and resolve your code

**Comment by NikhilSharma03** [comment]
@Akshima-Ghai Yes it will be fixed soon. I am currently working on desktop view and will start working on responsiveness as soon as possible.
