### ISSUE TITLE
Scroll to top and custom scrollbar button

### ISSUE THREAD

**Issue by kumarishalini6** [Akshima-Ghai/OneEducationalWebsiteForAll#48]
I want to add scroll to top and custom scrollbar button in each page

@Akshima-Ghai  can i work on this issue??

**Comment by Akshima-Ghai** [comment]
@kumarishalini6 issue assigned.

**Comment by NikhilSharma03** [comment]
Sorry, I accidentally linked the PR with the wrong issue. You can proceed with the issue. Thank you.

**Comment by kumarishalini6** [comment]
> Sorry, I accidentally linked the PR with the wrong issue. You can proceed with the issue. Thank you.

No issue

**Comment by kumarishalini6** [comment]
@Akshima-Ghai  is it ok or you want some changes?

https://user-images.githubusercontent.com/69043944/124348183-f52de300-db94-11eb-978c-84a735430d9d.mp4

**Comment by Akshima-Ghai** [comment]
@kumarishalini6  change the animation applied on learnZania, that line revolving around doesn't look good and the time for login animation makes it look weird when the navbar changes from black to white, just make sure to update these changes

**Comment by kumarishalini6** [comment]
> @kumarishalini6 change the animation applied on learnZania, that line revolving around doesn't look good and the time for login animation makes it look weird when the navbar changes from black to white, just make sure to update these changes

These all are not my animation I'll change all this when I applied animation at home page this issue is only about scroll to top button and custom Scrollbar

**Comment by AmanBisht01** [comment]
Can i change the animation applied on learnzania.
