### ISSUE TITLE
PR Template

### ISSUE THREAD

**Issue by NikhilSharma03** [Akshima-Ghai/OneEducationalWebsiteForAll#50]
## Description

- Currently, many of the PR's don't have any descriptions or any supporting tests. It's always a good practice to give a description of the changes you have made since it gives the reviewer a better understanding of the issue you have solved.

## Changes Required

** We can define a PR template which consists of sections such as **
- This PR fixes :
- Description :
- Changes Made: 
   If it's a change in UI. Would be best to add images of UI as well.
- (Optional) Note For Reviewers :

**Comment by pranjay-poddar** [comment]
I would like to work on this.

**Comment by deeqakkk** [comment]
Assigned for 2 days!
