### ISSUE TITLE
Add Badges in README.md 

### ISSUE THREAD

**Issue by Akash20x** [Akshima-Ghai/OneEducationalWebsiteForAll#55]
I want to add badges in top section of readme which shows no of stars, issues, pr, open issues and closes issues, maintained and many more. Through these badges your README.md looks cool.

**Comment by Akash20x** [comment]
@Akshima-Ghai Please assign me this issue

**Comment by Akshima-Ghai** [comment]
@Akash20x issue assigned

**Comment by Akash20x** [comment]
@Akshima-Ghai Please check my pull request

**Comment by Akshima-Ghai** [comment]
@Akash20x in the badges, why is it written: "Made with Python" ?

**Comment by Akash20x** [comment]
> @Akash20x in the badges, why is it written: "Made with Python" ?

I will send another pull request with all correction.

**Comment by pranjay-poddar** [comment]
please assign this task to me

**Comment by Akash20x** [comment]
> please assign this task to me

I already assigned for this task
