### ISSUE TITLE
Add "Back to top" button in all the required pages.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#69]
Maintain the theme of project.
Feel free to ask if have any doubt.

**Comment by AmanBisht01** [comment]
Please assign this issue to me..

**Comment by Akshima-Ghai** [comment]
@AmanBisht01 issue assigned

**Comment by AmanBisht01** [comment]
@deeqakkk @Akshima-Ghai please review my PR.

**Comment by deeqakkk** [comment]
@AmanBisht01 Your PR is successfully merged, Keep up the good work.
