### ISSUE TITLE
Upgrade Footer section.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#80]
Reference:
https://dribbble.com/shots/2580790-Contact-Section

Feel free to do minor tweaks but final output should resembling with refernce.
And also you can ask anything if you want.

**Comment by deeqakkk** [comment]
![image](https://user-images.githubusercontent.com/78724676/124398814-61dfe380-dd35-11eb-87ce-f490e5e0969d.png)
Delete this much section as well, while working on this issue.

**Comment by urmi-256** [comment]
Please assign me this issue.

**Comment by Akshima-Ghai** [comment]
@urmi-256 issue assigned

**Comment by urmi-256** [comment]
Uploading 2021-07-06 12-04-36.mp4…

Have made something like this. Is it ok?

**Comment by urmi-256** [comment]
https://user-images.githubusercontent.com/71149323/124563518-b8e0d800-de5d-11eb-8fdf-20819f194ca5.mp4

Have made like this. Is it ok ?

**Comment by Akshima-Ghai** [comment]
yes it's looking great, just try with a different shade of red color

**Comment by Akshima-Ghai** [comment]
@urmi-256

**Comment by urmi-256** [comment]
@Akshima-Ghai    Is this looking fine?
![Screenshot (158)](https://user-images.githubusercontent.com/71149323/124573040-cd759e00-de66-11eb-929f-6d730aee3214.png)

**Comment by Akshima-Ghai** [comment]
yes , looking good . Great work
