### ISSUE TITLE
Add a Pre-Loader to our website.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#81]
Reference:
https://medium.muz.li/top-30-most-captivating-preloaders-for-your-website-95ed1beff99d
Take time that you need for it like 3-4 days but it should look decent.

**Comment by Swastik1710** [comment]
Hey, can u please assign this issue to me.

**Comment by Subhradeep10** [comment]
Can I work on it?

**Comment by Akshima-Ghai** [comment]
yes @Subhradeep10 , go ahead . issue assigned

**Comment by deeqakkk** [comment]
@Subhradeep10 any updates?

**Comment by Subhradeep10** [comment]
@deeqakkk Loading screen is uploading on the top right corner but not on the center else its disturbing the whole react app

**Comment by Subhradeep10** [comment]
@deeqakkk anyone else can go with it

**Comment by deeqakkk** [comment]
It's okay @Subhradeep10 , atleast you tried.👏

**Comment by shrihari-07** [comment]
Can I try it? @deeqakkk

**Comment by deeqakkk** [comment]
@shrihari-07 yes sure, good luck💯

**Comment by shrihari-07** [comment]
@deeqakkk I have managed to add the pre-loader. I just wanted to ask if I have to add it for all pages or should I add the pre-loader only to the home page?

**Comment by Akshima-Ghai** [comment]
@shrihari-07  add it to all the pages

**Comment by deeqakkk** [comment]
@shrihari-07 really nice , you did it so quick👏
for now add pre loader just to our home page.

**Comment by shrihari-07** [comment]
@deeqakkk below is the screen cast of how the pre-loader looks like. Let me know if the design, colour or duration of the pre loader has to be changed.
https://user-images.githubusercontent.com/67782171/125119987-747c6300-e10f-11eb-98c6-ccca81a51014.mp4

**Comment by shrihari-07** [comment]
@deeqakkk I've completed adding preloader to the home page and made a pull request.
