### ISSUE TITLE
Update Navbar and fix Color theme issue in mobile view.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#82]
![image](https://user-images.githubusercontent.com/78724676/124398658-838c9b00-dd34-11eb-836f-2e182fde8cb9.png)

Update navbar to look more like this in ss provided(color should be same as our project instead of blue), and also maintain color theme when size is reduced to mobile view.

**Comment by AmanBisht01** [comment]
Please assign this issue to me...

**Comment by Akshima-Ghai** [comment]
@AmanBisht01 issue assigned
