### ISSUE TITLE
Adding Code of Conduct file

### ISSUE THREAD

**Issue by aakankshabhende** [Akshima-Ghai/OneEducationalWebsiteForAll#85]

**Comment by deeqakkk** [comment]
@aakankshabhende  always try to put description  while opening a issue.
It helps both reviewer as well as contributor.

**Comment by aakankshabhende** [comment]
Creating a Code of Conduct which everyone must abide by and mentioning the Scope of this Code of Conduct.

**Comment by swathi-469** [comment]
Please assign this to me I would like to work on this issue

**Comment by Akshima-Ghai** [comment]
@swathi-469 issue assigned

**Comment by aakankshabhende** [comment]
@Akshima-Ghai  Mam I raised this issue first

**Comment by aakankshabhende** [comment]
I created it

**Comment by Akshima-Ghai** [comment]
For working, you need to also ask to assign the issue, if you have started working on the issue, we can ask @swathi-469 to work on a different issue, but pls keep that in mind for future references. And also do reply to this comment so that we can assign you the task . @aakankshabhende

**Comment by aakankshabhende** [comment]
@Akshima-Ghai Mam please assign me this issue

> For working, you need to also ask to assign the issue, if you have started working on the issue, we can ask @swathi-469 to work on a different issue, but pls keep that in mind for future references. And also do reply to this comment so that we can assign you the task . @aakankshabhende

**Comment by Akshima-Ghai** [comment]
@aakankshabhende issue assigned

**Comment by aakankshabhende** [comment]
Thanks @Akshima-Ghai mam

**Comment by Akshima-Ghai** [comment]
@swathi-469 sorry for the inconvenience caused, try working on different issue

**Comment by swathi-469** [comment]
but I am ready with my work just ahead of making the pull request

**Comment by Akshima-Ghai** [comment]
ok @swathi-469 and @aakankshabhende pls work together, we will consider both prs made

**Comment by swathi-469** [comment]
yeah thank you

**Comment by swathi-469** [comment]
I have made my pull request can you check it
