### ISSUE TITLE
Can I work on the Navbar

### ISSUE THREAD

**Issue by neha030** [Akshima-Ghai/OneEducationalWebsiteForAll#9]
I want to design the navbar which will contain the link to different pages.

**Comment by Akshima-Ghai** [comment]
@neha030 issue assigned. All the best, try to learn maximum from the opportunity given.

**Comment by Akshima-Ghai** [comment]
share the screenshot

**Comment by neha030** [comment]
![Screenshot (144)](https://user-images.githubusercontent.com/72595335/123815380-10d68680-d914-11eb-91c4-347ce6c98f98.png)

**Comment by neha030** [comment]
On Hovering 

![image](https://user-images.githubusercontent.com/72595335/123815670-4aa78d00-d914-11eb-9b8e-708121cef243.png)

**Comment by Akshima-Ghai** [comment]
@neha030  you have done a great job, but this does not match the theme of the main page, try to be more focused on the theme
You are doing great and will definitely do better, try to make it match the theme of the main page or choose another issue if u want to. Looking forward to seeing your creativity and your enthusiasm for the project. GOOD LUCK

**Comment by jayeshpurohit12** [comment]
I have an idea of navbar design with given theme can i go ahead

**Comment by Akshima-Ghai** [comment]
@jayeshpurohit12 go ahead , this is your chance , give it your best shot , ALL THE BEST

**Comment by jayeshpurohit12** [comment]
https://user-images.githubusercontent.com/61271857/124245085-7b362500-dad4-11eb-836f-7b39c2c5b694.mp4

if you have any suggestions that you want change please tell me because i take care of theme then make change on that

**Comment by deeqakkk** [comment]
@jayeshpurohit12 It's really great,  you did it nicely!, just change the text style "you can learn anything" to bold style or try changing its font-weight to seek the attention .

**Comment by Akshima-Ghai** [comment]
great work @jayeshpurohit12, just try to try some different colors for home, courses......... when you hover over them, otherwise its looking good .

**Comment by jayeshpurohit12** [comment]
> different colors for home, courses......... when you hover over them, otherwise its looking good .

ok thanks for your information and i am adding some animation too

**Comment by jayeshpurohit12** [comment]
> great work @jayeshpurohit12, just try to try some different colors for home, courses......... when you hover over them, otherwise its looking good .

https://user-images.githubusercontent.com/61271857/124277542-ffe76a00-daf9-11eb-9d0b-ee95d79aa2ad.mp4

All Navbar changes done.
