### ISSUE TITLE
Add logo.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#90]
Update header section with this logo on the left of "LearnZania".

Logo's DIrectory:
src\assets\logos\1.png

**Comment by HarshitPandey251** [comment]
I want to work on it @deeqakkk

**Comment by HarshitPandey251** [comment]
![zzz6](https://user-images.githubusercontent.com/69616901/124865921-2d8c5180-dfd9-11eb-94eb-d4d7fa2c475a.jpg)
This is how it look

**Comment by deeqakkk** [comment]
@HarshitPandey251 You need not to remove "LearnZania" , just add logo in the left of it.

**Comment by HarshitPandey251** [comment]
okk

**Comment by shrihari-07** [comment]
I want to work on it @deeqakkk

**Comment by deeqakkk** [comment]
@shrihari-07 your interest to contribute is appreciated but this issue is already assigned.
