### ISSUE TITLE
Update Readme file.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#91]
Changes required:
1. Update tech stacks to MongoDB, React, Express, NodeJs.
2. Update this section to make it look good as well as informative
![image](https://user-images.githubusercontent.com/78724676/124857545-1c881400-dfca-11eb-9ebf-067bd99f486e.png)
Feel free to use your creative skills and google as well.

**Comment by SarveshLimaye** [comment]
hey i am contributor from devincept and would love to work on this issue. Please assign me this issue.

**Comment by Akshima-Ghai** [comment]
@SarveshLimaye issue assigned

**Comment by deeqakkk** [comment]
@SarveshLimaye it's already been 4 days, any updates regarding progress?

**Comment by Harshal0902** [comment]
@Akshima-Ghai I am one of the contributor from devincept, can i work on this issue?

**Comment by Akshima-Ghai** [comment]
@Harshal0902 issue assigned
