### ISSUE TITLE
Develop Features page.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#92]
We need something like this 👇
Reference:
![image](https://user-images.githubusercontent.com/78724676/124858295-64f40180-dfcb-11eb-80fe-8047a8327859.png)

The clear image here:
https://www.figma.com/file/KLVAVkyIbVTcOovNqA20UB/Untitled?node-id=0%3A1

2 Contributors can work on this together as well.

**Comment by jayeshpurohit12** [comment]
Please assign this issue to me

**Comment by urmi-256** [comment]
Can I work on this too?

**Comment by Akshima-Ghai** [comment]
@jayeshpurohit12 and @urmi-256 issue assigned, pls work together on this issue and try to finish this asap

**Comment by urmi-256** [comment]
Okk.

**Comment by jayeshpurohit12** [comment]
Okk

**Comment by urmi-256** [comment]
Is the feature on the name bar the same feature page which we want to create?

**Comment by Akshima-Ghai** [comment]
yes @urmi-256
