### ISSUE TITLE
Change color theme of "Get Started Page".

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#93]
Changes required:
1.Change  blusish shade to our color theme i.e shade of red.
2.Change image at center with a new one (You can look on some free images website)
3.Change the elements how it is displayed ( You can change according to yourself) but it should look decent.
![image](https://user-images.githubusercontent.com/78724676/124859011-b650c080-dfcc-11eb-8854-b7b143d7aced.png)

Sumbit a Screenshot or a Video before making a PR.

**Comment by urmi-256** [comment]
Can I work on this?

**Comment by SarveshLimaye** [comment]
Hey i am contributor from devincept and would love to work on this issue. Pls assign me with following issue.

**Comment by Akshima-Ghai** [comment]
issue assigned @SarveshLimaye

**Comment by SarveshLimaye** [comment]
![screencapture-localhost-3000-section-2021-07-09-14_06_34 jpeg (1)](https://user-images.githubusercontent.com/74766567/125068511-2ea1a980-e0d3-11eb-9c43-39f6b2b7cfd5.png)

**Comment by Akshima-Ghai** [comment]
it's looking good, just try with a light shade of red, inside the boxes. @SarveshLimaye . Good Work , keep it up

**Comment by SarveshLimaye** [comment]
Yes sure

**Comment by SarveshLimaye** [comment]
![screencapture-localhost-3000-section-2021-07-09-17_11_46 (1)](https://user-images.githubusercontent.com/74766567/125073165-2e0c1180-e0d9-11eb-9d54-6d8f4058eb74.png)

**Comment by Akshima-Ghai** [comment]
yup , it's looking good @SarveshLimaye
