### ISSUE TITLE
Design  two SignUp forms. One Teacher and one for student.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#94]
~Color theme should be maintained.
~All the necessary fields should be there for respective forms( Research a bit before starting to code)
~Create a section that one user click on sign up he/she should receive options to "SignUp as a teacher" or "Signup as a student/learner".

Feel free to ask if you have any doubt or have some idea to share.

**Comment by heet-kumar** [comment]
@deeqakkk any where you have hosted this project then provide the link of the website

**Comment by heet-kumar** [comment]
because i want to see your website once .

**Comment by toth2000** [comment]
> @deeqakkk any where you have hosted this project then provide the link of the website

Clone the git repo on your machine and follow the instructions given in the readme file.

**Comment by Swastik1710** [comment]
Hey @deeqakkk , I would love to work on this issue. Could you please assign it to me ?

**Comment by Akshima-Ghai** [comment]
@Swastik1710 issue assigned.
