### ISSUE TITLE
Remove whitespace from  around footer section.

### ISSUE THREAD

**Issue by deeqakkk** [Akshima-Ghai/OneEducationalWebsiteForAll#95]
![image](https://user-images.githubusercontent.com/78724676/124861109-89061180-dfd0-11eb-8f74-d0fc16a793db.png)
 Remove White space highlighted with blue color to occupy 100% width.

**Comment by HarshitPandey251** [comment]
assign this to me @deeqakkk

**Comment by HarshitPandey251** [comment]
![zzz8](https://user-images.githubusercontent.com/69616901/124870556-89a6a400-dfe0-11eb-9af9-ea91f64520f7.jpg)
This is how it look

**Comment by Akshima-Ghai** [comment]
@HarshitPandey251 issue assigned , create a pr of the changes made
